import type { AmenityKey } from "./amenities";
import type { TravelerProfileId } from "./traveler-profiles";

export type Accommodation = {
  slug: string;
  name: string;
  image: string;
  distanceFromSanctuary: string;
  walkingMinutes: number;
  coordinates: { lat: number; lng: number };
  mapPosition: { x: number; y: number };
  pricePerNight: number;
  rating: number;
  reviewCount: number;
  amenities: AmenityKey[];
  maxGuests: number;
  roomCount: number;
  bedCount: number;
  isAccessible: boolean;
  suitableFor: TravelerProfileId[];
  highlightBadge?: string;
};

export const MAP_HIGHLIGHT_ACCOMMODATION: Accommodation = {
  slug: "conforto-para-toda-familia",
  name: "Conforto para toda a família",
  image:
    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=600",
  distanceFromSanctuary: "350 m do Santuário",
  walkingMinutes: 4,
  coordinates: { lat: -22.864998, lng: -45.223595 },
  mapPosition: { x: 32, y: 38 },
  pricePerNight: 280,
  rating: 9.2,
  reviewCount: 214,
  amenities: ["familyFriendly", "breakfast"],
  maxGuests: 4,
  roomCount: 1,
  bedCount: 2,
  isAccessible: false,
  suitableFor: ["familia-criancas", "cafe-manha"],
};

export const ACCOMMODATIONS: Accommodation[] = [
  {
    slug: "hotel-rainha-do-brasil",
    name: "Hotel Rainha do Brasil",
    image:
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "400 m do Santuário",
    walkingMinutes: 5,
    coordinates: { lat: -22.868719, lng: -45.222066 },
    mapPosition: { x: 61, y: 24 },
    pricePerNight: 320,
    rating: 4.8,
    reviewCount: 612,
    amenities: ["breakfast", "parking"],
    maxGuests: 2,
    roomCount: 1,
    bedCount: 1,
    isAccessible: false,
    suitableFor: ["cafe-manha"],
  },
  {
    slug: "pousada-mae-aparecida",
    name: "Pousada Mãe Aparecida",
    image:
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "450 m do Santuário",
    walkingMinutes: 6,
    coordinates: { lat: -22.871252, lng: -45.227201 },
    mapPosition: { x: 17, y: 34 },
    pricePerNight: 250,
    rating: 4.9,
    reviewCount: 387,
    amenities: ["parking", "familyFriendly"],
    maxGuests: 3,
    roomCount: 1,
    bedCount: 2,
    isAccessible: false,
    suitableFor: ["familia-criancas"],
  },
  {
    slug: "hotel-sao-miguel",
    name: "Hotel São Miguel",
    image:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "600 m do Santuário",
    walkingMinutes: 7,
    coordinates: { lat: -22.865898, lng: -45.220326 },
    mapPosition: { x: 74, y: 40 },
    pricePerNight: 290,
    rating: 4.7,
    reviewCount: 521,
    amenities: ["breakfast", "accessible"],
    maxGuests: 4,
    roomCount: 1,
    bedCount: 2,
    isAccessible: true,
    suitableFor: ["idosos", "acessibilidade", "cafe-manha"],
  },
  {
    slug: "pousada-do-devoto",
    name: "Pousada do Devoto",
    image:
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "850 m do Santuário",
    walkingMinutes: 10,
    coordinates: { lat: -22.862581, lng: -45.231575 },
    mapPosition: { x: 12, y: 20 },
    pricePerNight: 220,
    rating: 4.6,
    reviewCount: 298,
    amenities: ["pool", "parking"],
    maxGuests: 6,
    roomCount: 2,
    bedCount: 3,
    isAccessible: false,
    suitableFor: ["familia-criancas"],
  },
  {
    slug: "hotel-portal-da-fe",
    name: "Hotel Portal da Fé",
    image:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "500 m do Santuário",
    walkingMinutes: 6,
    coordinates: { lat: -22.862954, lng: -45.226413 },
    mapPosition: { x: 38, y: 18 },
    pricePerNight: 310,
    rating: 4.8,
    reviewCount: 466,
    amenities: ["breakfast", "accessible"],
    maxGuests: 2,
    roomCount: 1,
    bedCount: 1,
    isAccessible: true,
    suitableFor: ["idosos", "acessibilidade", "cafe-manha"],
  },
  {
    slug: "pousada-bom-caminho",
    name: "Pousada Bom Caminho",
    image:
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "700 m do Santuário",
    walkingMinutes: 8,
    coordinates: { lat: -22.871265, lng: -45.221188 },
    mapPosition: { x: 80, y: 62 },
    pricePerNight: 240,
    rating: 4.7,
    reviewCount: 320,
    amenities: ["familyFriendly", "breakfast"],
    maxGuests: 4,
    roomCount: 2,
    bedCount: 2,
    isAccessible: false,
    suitableFor: ["familia-criancas", "cafe-manha"],
  },
  {
    slug: "recanto-da-padroeira",
    name: "Recanto da Padroeira · Casa Inteira",
    image:
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "5 min a pé da Passarela da Fé",
    walkingMinutes: 5,
    coordinates: { lat: -22.868429, lng: -45.229265 },
    mapPosition: { x: 44, y: 78 },
    pricePerNight: 980,
    rating: 4.98,
    reviewCount: 52,
    amenities: ["wholeHouse", "vanSpot", "accessible"],
    maxGuests: 22,
    roomCount: 6,
    bedCount: 16,
    isAccessible: true,
    suitableFor: ["grupo-romarias", "estacionamento-van", "acessibilidade"],
    highlightBadge: "Mais procurada p/ romarias",
  },
  {
    slug: "hospedagem-familia-aparecida",
    name: "Hospedagem Família Aparecida",
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "800 m do Santuário",
    walkingMinutes: 9,
    coordinates: { lat: -22.871773, lng: -45.230564 },
    mapPosition: { x: 25, y: 72 },
    pricePerNight: 260,
    rating: 4.5,
    reviewCount: 178,
    amenities: ["breakfast", "familyFriendly"],
    maxGuests: 5,
    roomCount: 2,
    bedCount: 3,
    isAccessible: false,
    suitableFor: ["familia-criancas", "cafe-manha"],
  },
  {
    slug: "casa-da-romaria",
    name: "Casa da Romaria",
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "1,1 km do Santuário",
    walkingMinutes: 13,
    coordinates: { lat: -22.862529, lng: -45.216819 },
    mapPosition: { x: 88, y: 18 },
    pricePerNight: 1240,
    rating: 4.9,
    reviewCount: 96,
    amenities: ["wholeHouse", "vanSpot", "parking"],
    maxGuests: 30,
    roomCount: 9,
    bedCount: 24,
    isAccessible: false,
    suitableFor: ["grupo-romarias", "estacionamento-van"],
    highlightBadge: "Recebe ônibus",
  },
  {
    slug: "hotel-nossa-senhora",
    name: "Hotel Nossa Senhora",
    image:
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "300 m do Santuário",
    walkingMinutes: 4,
    coordinates: { lat: -22.864423, lng: -45.224793 },
    mapPosition: { x: 46, y: 30 },
    pricePerNight: 340,
    rating: 4.9,
    reviewCount: 738,
    amenities: ["breakfast", "accessible", "parking"],
    maxGuests: 3,
    roomCount: 1,
    bedCount: 2,
    isAccessible: true,
    suitableFor: ["idosos", "acessibilidade", "cafe-manha"],
    highlightBadge: "Mais perto do Santuário",
  },
  {
    slug: "pousada-passarela",
    name: "Pousada Passarela da Fé",
    image:
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "550 m do Santuário",
    walkingMinutes: 7,
    coordinates: { lat: -22.865479, lng: -45.23073 },
    mapPosition: { x: 22, y: 52 },
    pricePerNight: 270,
    rating: 4.6,
    reviewCount: 241,
    amenities: ["breakfast", "familyFriendly", "accessible"],
    maxGuests: 6,
    roomCount: 2,
    bedCount: 4,
    isAccessible: true,
    suitableFor: ["familia-criancas", "acessibilidade", "cafe-manha"],
  },
  {
    slug: "hotel-monte-carmelo",
    name: "Hotel Monte Carmelo",
    image:
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "300 m do Santuário",
    walkingMinutes: 4,
    coordinates: { lat: -22.867184, lng: -45.224918 },
    mapPosition: { x: 58, y: 42 },
    pricePerNight: 305,
    rating: 4.7,
    reviewCount: 388,
    amenities: ["breakfast", "parking", "accessible"],
    maxGuests: 3,
    roomCount: 1,
    bedCount: 2,
    isAccessible: true,
    suitableFor: ["idosos", "acessibilidade", "cafe-manha"],
  },
  {
    slug: "pousada-luz-do-amanhecer",
    name: "Pousada Luz do Amanhecer",
    image:
      "https://images.unsplash.com/photo-1576354302919-96748cb8299e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "480 m do Santuário",
    walkingMinutes: 6,
    coordinates: { lat: -22.864212, lng: -45.226703 },
    mapPosition: { x: 37, y: 61 },
    pricePerNight: 235,
    rating: 4.5,
    reviewCount: 176,
    amenities: ["breakfast", "familyFriendly"],
    maxGuests: 5,
    roomCount: 2,
    bedCount: 3,
    isAccessible: false,
    suitableFor: ["familia-criancas", "cafe-manha"],
  },
  {
    slug: "hospedaria-sao-benedito",
    name: "Hospedaria São Benedito",
    image:
      "https://images.unsplash.com/photo-1568495248636-6432b97bd949?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "700 m do Santuário",
    walkingMinutes: 9,
    coordinates: { lat: -22.861945, lng: -45.221338 },
    mapPosition: { x: 66, y: 74 },
    pricePerNight: 190,
    rating: 4.4,
    reviewCount: 143,
    amenities: ["parking", "vanSpot", "familyFriendly"],
    maxGuests: 12,
    roomCount: 4,
    bedCount: 8,
    isAccessible: false,
    suitableFor: ["grupo-romarias", "estacionamento-van"],
  },
  {
    slug: "hotel-fonte-da-esperanca",
    name: "Hotel Fonte da Esperança",
    image:
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "620 m do Santuário",
    walkingMinutes: 8,
    coordinates: { lat: -22.860773, lng: -45.218994 },
    mapPosition: { x: 86, y: 74 },
    pricePerNight: 410,
    rating: 4.9,
    reviewCount: 502,
    amenities: ["breakfast", "parking", "pool", "securedBooking"],
    maxGuests: 4,
    roomCount: 2,
    bedCount: 2,
    isAccessible: true,
    suitableFor: ["familia-criancas", "acessibilidade", "cafe-manha"],
    highlightBadge: "Melhor avaliado",
  },
  {
    slug: "pousada-recanto-do-peregrino",
    name: "Pousada Recanto do Peregrino",
    image:
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "850 m do Santuário",
    walkingMinutes: 11,
    coordinates: { lat: -22.858412, lng: -45.229517 },
    mapPosition: { x: 14, y: 80 },
    pricePerNight: 165,
    rating: 4.3,
    reviewCount: 98,
    amenities: ["breakfast", "parking"],
    maxGuests: 2,
    roomCount: 1,
    bedCount: 1,
    isAccessible: false,
    suitableFor: ["cafe-manha"],
  },
  {
    slug: "hotel-jardim-das-oliveiras",
    name: "Hotel Jardim das Oliveiras",
    image:
      "https://images.unsplash.com/photo-1667125095636-dce94dcbdd96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "540 m do Santuário",
    walkingMinutes: 7,
    coordinates: { lat: -22.869934, lng: -45.219776 },
    mapPosition: { x: 90, y: 46 },
    pricePerNight: 350,
    rating: 4.8,
    reviewCount: 427,
    amenities: ["breakfast", "parking", "accessible", "securedBooking"],
    maxGuests: 4,
    roomCount: 2,
    bedCount: 3,
    isAccessible: true,
    suitableFor: ["idosos", "acessibilidade", "familia-criancas", "cafe-manha"],
  },
  {
    slug: "casa-de-repouso-santa-clara",
    name: "Casa Santa Clara",
    image:
      "https://images.unsplash.com/photo-1630660664869-c9d3cc676880?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "760 m do Santuário",
    walkingMinutes: 10,
    coordinates: { lat: -22.862108, lng: -45.232244 },
    mapPosition: { x: 10, y: 62 },
    pricePerNight: 720,
    rating: 4.7,
    reviewCount: 64,
    amenities: ["wholeHouse", "parking", "familyFriendly", "vanSpot"],
    maxGuests: 14,
    roomCount: 5,
    bedCount: 9,
    isAccessible: false,
    suitableFor: ["grupo-romarias", "estacionamento-van", "familia-criancas"],
  },
  {
    slug: "pousada-porta-do-ceu",
    name: "Pousada Porta do Céu",
    image:
      "https://images.unsplash.com/photo-1629140727571-9b5c6f6267b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "890 m do Santuário",
    walkingMinutes: 12,
    coordinates: { lat: -22.872356, lng: -45.220145 },
    mapPosition: { x: 70, y: 11 },
    pricePerNight: 210,
    rating: 4.5,
    reviewCount: 187,
    amenities: ["breakfast", "familyFriendly", "parking"],
    maxGuests: 6,
    roomCount: 2,
    bedCount: 4,
    isAccessible: false,
    suitableFor: ["familia-criancas", "cafe-manha", "estacionamento-van"],
  },
  {
    slug: "hotel-caminho-de-fatima",
    name: "Hotel Caminho de Fátima",
    image:
      "https://images.unsplash.com/photo-1611892440504-42a792e24d32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "960 m do Santuário",
    walkingMinutes: 12,
    coordinates: { lat: -22.866027, lng: -45.234891 },
    mapPosition: { x: 9, y: 45 },
    pricePerNight: 280,
    rating: 4.6,
    reviewCount: 312,
    amenities: ["breakfast", "parking", "vanSpot", "accessible"],
    maxGuests: 18,
    roomCount: 7,
    bedCount: 12,
    isAccessible: true,
    suitableFor: [
      "grupo-romarias",
      "estacionamento-van",
      "acessibilidade",
      "cafe-manha",
    ],
  },
  {
    slug: "residencial-nossa-senhora-da-paz",
    name: "Residencial Nossa Senhora da Paz",
    image:
      "https://images.unsplash.com/photo-1711059985570-4c32ed12a12c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    distanceFromSanctuary: "420 m do Santuário",
    walkingMinutes: 5,
    coordinates: { lat: -22.866512, lng: -45.225384 },
    mapPosition: { x: 58, y: 60 },
    pricePerNight: 255,
    rating: 4.6,
    reviewCount: 229,
    amenities: ["breakfast", "accessible", "familyFriendly"],
    maxGuests: 4,
    roomCount: 2,
    bedCount: 3,
    isAccessible: true,
    suitableFor: ["idosos", "acessibilidade", "familia-criancas", "cafe-manha"],
  },
];
